name: Create report

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  create-report:
    runs-on: ubuntu-latest
    outputs:
      status: ${{ steps.set-output.outputs.status }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Python 3.x
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        pip install requests python-whois dnspython beautifulsoup4 selenium

    - name: Set up Chrome
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: 'stable'  # or specify a particular version if needed

    - name: Set up Chromedriver
      uses: nanasess/setup-chromedriver@v1
      with:
        chromedriver-version: 'latest'  # or specify a particular version if needed

    - name: Verify Chrome Installation
      run: |
        google-chrome --version
        chromedriver --version

    - name: Run Website Tests
      id: test
      run: python main.py
      continue-on-error: false  # Ensures the workflow stops on error

    - name: Set Output status
      id: set-output
      run: |
        if [[ -f error.log ]]; then
          echo "Error encountered in Website Tests"
          echo "::set-output name=status::error"
        else
          echo "::set-output name=status::success"
        fi

    - name: Commit and push report
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md
        git commit -m "Add generated report" -a || echo "No changes to commit"
        git push

    - name: Fail if error encountered
      if: steps.set-output.outputs.status == 'error'
      run: exit 1

