name: Create release

on:
  workflow_dispatch:

jobs:
  create-pdf:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyGithub # Add other dependencies as needed

    - name: Install pandoc and texlive
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc
        sudo apt-get install -y texlive-xetex

    - name: Generate and upload report
      run: python create_release.py
      env:
        PAT: ${{ secrets.PAT }}
