name: Generate PDF Report and Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libev-dev

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install markdown pdfkit aiohttp

    # You may also need to install wkhtmltopdf if using pdfkit
    - name: Install wkhtmltopdf
      run: |
        sudo apt-get install -y wkhtmltopdf

    - name: Run your script to generate report and create a release
      run: |
        python create_release.py
      env:
        PAT: ${{ secrets.PAT }}
