name: Generate PDF from README Markdown Table

on:
  push:
    branches:
      - main
    paths:
      - 'README.md'
 workflow_dispatch:
 
jobs:
  generate-pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install pandoc
        run: sudo apt-get -y install pandoc

      - name: Install texlive (for pdflatex)
        run: sudo apt-get -y install texlive-xetex

      - name: Convert Markdown to PDF
        run: pandoc -s README.md -o README.pdf

      - name: Upload PDF as artifact
        uses: actions/upload-artifact@v2
        with:
          name: README-pdf
          path: README.pdf

      - name: Commit and push PDF report
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.pdf
          git commit -m "Add generated PDF of README" -a || echo "No changes to commit"
          git push
